#undef TEMPCORR
#undef SAWTOOTH_COMP
#define LCD

#define PLL_FUDGE_NS 750
#define PLL_OFFSET_NTP 0x4000000
#define NTP_FUDGE_RX_US (-50)
#define NTP_FUDGE_TX_US 950

#define PLL_SLEW_DIV 1024L
#define PLL_SLEW_MAX 8192L
#define PLL_SLEW_SLOW_ZONE 0
#define PLL_RATE_DIV 256L
#undef PLL_DAMP
#define PLL_SKEW_MAX 32
